name: myapp

networks:
  default:
    name: myapp-network
    driver: bridge

services:
  immutable-log-server:
    build: .
    container_name: immutable-log-server
    ports:
      - 3000:3000
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - ./data:/app/data
      